### ISSUE TITLE
Tests in the "tests" folder don't run

### ISSUE THREAD

**Issue by kstenerud** [nguyenchr/atom-cargo-test-runner#12] opened 2016-01-31 20:22 UTC
The tests in `src/lib.rs` run just fine, but if I open a file in my tests folder like `tests/test_something.rs` and try to run it, I just get "0 passed, 0 failed, 0 ignored, 0 measured".

**Comment by binary132** [comment] 2016-03-13 15:48
Same.  When I run `cargo test` from the command line in the crate root, it runs the `tests/...` files just fine.

When I turned on the "Show Context Information" settings option and use this test runner, it shows:

```
Cargo binary:   /usr/local/bin/cargo
Root folder:    /Users/bodiesolomon/meta/dev/workspace/workshop/scratchpad/rust/env
Test file:      env_test.rs
PATH:           .:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:

... (the rest of the output is cut off and I can't scroll down.)
```

**Comment by binary132** [comment] 2016-03-13 15:52
This Issue is a duplicate of #4, where I left the solution in a comment.

**Comment by nguyenchr** [comment] 2016-04-25 23:40
this fix is now in the latest `v0.1.0` release, thanks for the help :)

**Closed as completed by nguyenchr** 2016-04-25 23:40 UTC
